const { defineConfig } = require('cypress')

module.exports = defineConfig({
  e2e: {
    baseUrl: 'http://localhost:3000',
  },
  experimentalStudio: true

})

// the experimentalStudio: true line allows me to interact with the app in the Cypress UI like a user would and it generates tests for me
// the tests generated by the experimental feature make sure that the app is working as expected
// I also added Jest/React Testing Library to the project to test the components in isolation